// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: tutorialpb/tutorial.proto

package tutorialpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrintStrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PrintStrRequest) Reset() {
	*x = PrintStrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrintStrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintStrRequest) ProtoMessage() {}

func (x *PrintStrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintStrRequest.ProtoReflect.Descriptor instead.
func (*PrintStrRequest) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{0}
}

func (x *PrintStrRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PrintStrResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PrintStrResponce) Reset() {
	*x = PrintStrResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrintStrResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintStrResponce) ProtoMessage() {}

func (x *PrintStrResponce) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintStrResponce.ProtoReflect.Descriptor instead.
func (*PrintStrResponce) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{1}
}

func (x *PrintStrResponce) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SaveImageUnaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceId     string `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImageBinary []byte `protobuf:"bytes,3,opt,name=image_binary,json=imageBinary,proto3" json:"image_binary,omitempty"`
}

func (x *SaveImageUnaryRequest) Reset() {
	*x = SaveImageUnaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveImageUnaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveImageUnaryRequest) ProtoMessage() {}

func (x *SaveImageUnaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveImageUnaryRequest.ProtoReflect.Descriptor instead.
func (*SaveImageUnaryRequest) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{2}
}

func (x *SaveImageUnaryRequest) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *SaveImageUnaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveImageUnaryRequest) GetImageBinary() []byte {
	if x != nil {
		return x.ImageBinary
	}
	return nil
}

type SaveImageUnaryResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveImageUnaryResponce) Reset() {
	*x = SaveImageUnaryResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveImageUnaryResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveImageUnaryResponce) ProtoMessage() {}

func (x *SaveImageUnaryResponce) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveImageUnaryResponce.ProtoReflect.Descriptor instead.
func (*SaveImageUnaryResponce) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{3}
}

type SaveImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*SaveImageRequest_Info
	//	*SaveImageRequest_ImageBinary
	Data isSaveImageRequest_Data `protobuf_oneof:"data"`
}

func (x *SaveImageRequest) Reset() {
	*x = SaveImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveImageRequest) ProtoMessage() {}

func (x *SaveImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveImageRequest.ProtoReflect.Descriptor instead.
func (*SaveImageRequest) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{4}
}

func (m *SaveImageRequest) GetData() isSaveImageRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SaveImageRequest) GetInfo() *ImageInfo {
	if x, ok := x.GetData().(*SaveImageRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (x *SaveImageRequest) GetImageBinary() []byte {
	if x, ok := x.GetData().(*SaveImageRequest_ImageBinary); ok {
		return x.ImageBinary
	}
	return nil
}

type isSaveImageRequest_Data interface {
	isSaveImageRequest_Data()
}

type SaveImageRequest_Info struct {
	Info *ImageInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type SaveImageRequest_ImageBinary struct {
	ImageBinary []byte `protobuf:"bytes,2,opt,name=image_binary,json=imageBinary,proto3,oneof"`
}

func (*SaveImageRequest_Info) isSaveImageRequest_Data() {}

func (*SaveImageRequest_ImageBinary) isSaveImageRequest_Data() {}

type ImageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceId string `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{5}
}

func (x *ImageInfo) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *ImageInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SaveImageResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveImageResponce) Reset() {
	*x = SaveImageResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveImageResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveImageResponce) ProtoMessage() {}

func (x *SaveImageResponce) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveImageResponce.ProtoReflect.Descriptor instead.
func (*SaveImageResponce) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{6}
}

type GetImageUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceId string `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
}

func (x *GetImageUrlRequest) Reset() {
	*x = GetImageUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageUrlRequest) ProtoMessage() {}

func (x *GetImageUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageUrlRequest.ProtoReflect.Descriptor instead.
func (*GetImageUrlRequest) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{7}
}

func (x *GetImageUrlRequest) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

type GetImageUrlResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageUrl string `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *GetImageUrlResponce) Reset() {
	*x = GetImageUrlResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageUrlResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageUrlResponce) ProtoMessage() {}

func (x *GetImageUrlResponce) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageUrlResponce.ProtoReflect.Descriptor instead.
func (*GetImageUrlResponce) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{8}
}

func (x *GetImageUrlResponce) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type SaveColorCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceId   string `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ColorCode string `protobuf:"bytes,3,opt,name=color_code,json=colorCode,proto3" json:"color_code,omitempty"`
}

func (x *SaveColorCodeRequest) Reset() {
	*x = SaveColorCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveColorCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveColorCodeRequest) ProtoMessage() {}

func (x *SaveColorCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveColorCodeRequest.ProtoReflect.Descriptor instead.
func (*SaveColorCodeRequest) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{9}
}

func (x *SaveColorCodeRequest) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *SaveColorCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveColorCodeRequest) GetColorCode() string {
	if x != nil {
		return x.ColorCode
	}
	return ""
}

type SaveColorCodeResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveColorCodeResponce) Reset() {
	*x = SaveColorCodeResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveColorCodeResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveColorCodeResponce) ProtoMessage() {}

func (x *SaveColorCodeResponce) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveColorCodeResponce.ProtoReflect.Descriptor instead.
func (*SaveColorCodeResponce) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{10}
}

type GetColorCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceId string `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
}

func (x *GetColorCodeRequest) Reset() {
	*x = GetColorCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetColorCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColorCodeRequest) ProtoMessage() {}

func (x *GetColorCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColorCodeRequest.ProtoReflect.Descriptor instead.
func (*GetColorCodeRequest) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{11}
}

func (x *GetColorCodeRequest) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

type GetColorCodeResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColorCode string `protobuf:"bytes,1,opt,name=color_code,json=colorCode,proto3" json:"color_code,omitempty"`
}

func (x *GetColorCodeResponce) Reset() {
	*x = GetColorCodeResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetColorCodeResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColorCodeResponce) ProtoMessage() {}

func (x *GetColorCodeResponce) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColorCodeResponce.ProtoReflect.Descriptor instead.
func (*GetColorCodeResponce) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{12}
}

func (x *GetColorCodeResponce) GetColorCode() string {
	if x != nil {
		return x.ColorCode
	}
	return ""
}

var File_tutorialpb_tutorial_proto protoreflect.FileDescriptor

var file_tutorialpb_tutorial_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x70, 0x62, 0x2f, 0x74, 0x75, 0x74,
	0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x2b, 0x0a, 0x0f, 0x50, 0x72,
	0x69, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a, 0x10, 0x50, 0x72, 0x69, 0x6e, 0x74,
	0x53, 0x74, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x6e, 0x0a, 0x15, 0x53, 0x61, 0x76, 0x65, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x42,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x61, 0x76, 0x65, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22,
	0x6f, 0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61,
	0x6c, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x0c, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0b, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x3f, 0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x61, 0x76, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x2f, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x69, 0x0a, 0x14, 0x53,
	0x61, 0x76, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x61, 0x76, 0x65, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22,
	0x30, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49,
	0x64, 0x22, 0x35, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x32, 0xa7, 0x04, 0x0a, 0x10, 0x54, 0x75, 0x72,
	0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a,
	0x08, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x12, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x53,
	0x74, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x53,
	0x74, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x0e,
	0x53, 0x61, 0x76, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x24,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x53,
	0x61, 0x76, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f,
	0x72, 0x69, 0x61, 0x6c, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x6e,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a,
	0x09, 0x53, 0x61, 0x76, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x53, 0x61, 0x76, 0x65,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x12, 0x56, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c,
	0x12, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c,
	0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72,
	0x69, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x0d, 0x53, 0x61, 0x76,
	0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74,
	0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65,
	0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x6e, 0x79, 0x6f, 0x38, 0x37,
	0x37, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2f,
	0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_tutorialpb_tutorial_proto_rawDescOnce sync.Once
	file_tutorialpb_tutorial_proto_rawDescData = file_tutorialpb_tutorial_proto_rawDesc
)

func file_tutorialpb_tutorial_proto_rawDescGZIP() []byte {
	file_tutorialpb_tutorial_proto_rawDescOnce.Do(func() {
		file_tutorialpb_tutorial_proto_rawDescData = protoimpl.X.CompressGZIP(file_tutorialpb_tutorial_proto_rawDescData)
	})
	return file_tutorialpb_tutorial_proto_rawDescData
}

var file_tutorialpb_tutorial_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_tutorialpb_tutorial_proto_goTypes = []interface{}{
	(*PrintStrRequest)(nil),        // 0: grpc_tutorial.PrintStrRequest
	(*PrintStrResponce)(nil),       // 1: grpc_tutorial.PrintStrResponce
	(*SaveImageUnaryRequest)(nil),  // 2: grpc_tutorial.SaveImageUnaryRequest
	(*SaveImageUnaryResponce)(nil), // 3: grpc_tutorial.SaveImageUnaryResponce
	(*SaveImageRequest)(nil),       // 4: grpc_tutorial.SaveImageRequest
	(*ImageInfo)(nil),              // 5: grpc_tutorial.ImageInfo
	(*SaveImageResponce)(nil),      // 6: grpc_tutorial.SaveImageResponce
	(*GetImageUrlRequest)(nil),     // 7: grpc_tutorial.GetImageUrlRequest
	(*GetImageUrlResponce)(nil),    // 8: grpc_tutorial.GetImageUrlResponce
	(*SaveColorCodeRequest)(nil),   // 9: grpc_tutorial.SaveColorCodeRequest
	(*SaveColorCodeResponce)(nil),  // 10: grpc_tutorial.SaveColorCodeResponce
	(*GetColorCodeRequest)(nil),    // 11: grpc_tutorial.GetColorCodeRequest
	(*GetColorCodeResponce)(nil),   // 12: grpc_tutorial.GetColorCodeResponce
}
var file_tutorialpb_tutorial_proto_depIdxs = []int32{
	5,  // 0: grpc_tutorial.SaveImageRequest.info:type_name -> grpc_tutorial.ImageInfo
	0,  // 1: grpc_tutorial.TurtorialService.PrintStr:input_type -> grpc_tutorial.PrintStrRequest
	2,  // 2: grpc_tutorial.TurtorialService.SaveImageUnary:input_type -> grpc_tutorial.SaveImageUnaryRequest
	4,  // 3: grpc_tutorial.TurtorialService.SaveImage:input_type -> grpc_tutorial.SaveImageRequest
	7,  // 4: grpc_tutorial.TurtorialService.GetImageUrl:input_type -> grpc_tutorial.GetImageUrlRequest
	9,  // 5: grpc_tutorial.TurtorialService.SaveColorCode:input_type -> grpc_tutorial.SaveColorCodeRequest
	11, // 6: grpc_tutorial.TurtorialService.GetColorCode:input_type -> grpc_tutorial.GetColorCodeRequest
	1,  // 7: grpc_tutorial.TurtorialService.PrintStr:output_type -> grpc_tutorial.PrintStrResponce
	3,  // 8: grpc_tutorial.TurtorialService.SaveImageUnary:output_type -> grpc_tutorial.SaveImageUnaryResponce
	6,  // 9: grpc_tutorial.TurtorialService.SaveImage:output_type -> grpc_tutorial.SaveImageResponce
	8,  // 10: grpc_tutorial.TurtorialService.GetImageUrl:output_type -> grpc_tutorial.GetImageUrlResponce
	10, // 11: grpc_tutorial.TurtorialService.SaveColorCode:output_type -> grpc_tutorial.SaveColorCodeResponce
	12, // 12: grpc_tutorial.TurtorialService.GetColorCode:output_type -> grpc_tutorial.GetColorCodeResponce
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_tutorialpb_tutorial_proto_init() }
func file_tutorialpb_tutorial_proto_init() {
	if File_tutorialpb_tutorial_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tutorialpb_tutorial_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrintStrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tutorialpb_tutorial_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrintStrResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tutorialpb_tutorial_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveImageUnaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tutorialpb_tutorial_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveImageUnaryResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tutorialpb_tutorial_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tutorialpb_tutorial_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tutorialpb_tutorial_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveImageResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tutorialpb_tutorial_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImageUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tutorialpb_tutorial_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImageUrlResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tutorialpb_tutorial_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveColorCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tutorialpb_tutorial_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveColorCodeResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tutorialpb_tutorial_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetColorCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tutorialpb_tutorial_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetColorCodeResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tutorialpb_tutorial_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*SaveImageRequest_Info)(nil),
		(*SaveImageRequest_ImageBinary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tutorialpb_tutorial_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tutorialpb_tutorial_proto_goTypes,
		DependencyIndexes: file_tutorialpb_tutorial_proto_depIdxs,
		MessageInfos:      file_tutorialpb_tutorial_proto_msgTypes,
	}.Build()
	File_tutorialpb_tutorial_proto = out.File
	file_tutorialpb_tutorial_proto_rawDesc = nil
	file_tutorialpb_tutorial_proto_goTypes = nil
	file_tutorialpb_tutorial_proto_depIdxs = nil
}
