// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: tutorialpb/tutorial.proto

package tutorialpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrintStrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PrintStrRequest) Reset() {
	*x = PrintStrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrintStrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintStrRequest) ProtoMessage() {}

func (x *PrintStrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintStrRequest.ProtoReflect.Descriptor instead.
func (*PrintStrRequest) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{0}
}

func (x *PrintStrRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PrintStrResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PrintStrResponce) Reset() {
	*x = PrintStrResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tutorialpb_tutorial_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrintStrResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintStrResponce) ProtoMessage() {}

func (x *PrintStrResponce) ProtoReflect() protoreflect.Message {
	mi := &file_tutorialpb_tutorial_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintStrResponce.ProtoReflect.Descriptor instead.
func (*PrintStrResponce) Descriptor() ([]byte, []int) {
	return file_tutorialpb_tutorial_proto_rawDescGZIP(), []int{1}
}

func (x *PrintStrResponce) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_tutorialpb_tutorial_proto protoreflect.FileDescriptor

var file_tutorialpb_tutorial_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x70, 0x62, 0x2f, 0x74, 0x75, 0x74,
	0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x2b, 0x0a, 0x0f, 0x50, 0x72,
	0x69, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a, 0x10, 0x50, 0x72, 0x69, 0x6e, 0x74,
	0x53, 0x74, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x58, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x12, 0x4d, 0x0a, 0x08, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x12, 0x1e, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x50, 0x72, 0x69,
	0x6e, 0x74, 0x53, 0x74, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x50, 0x72, 0x69,
	0x6e, 0x74, 0x53, 0x74, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x00, 0x42,
	0x36, 0x5a, 0x34, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x6e, 0x79, 0x6f, 0x38, 0x37, 0x37, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2f, 0x74, 0x75, 0x74,
	0x6f, 0x72, 0x69, 0x61, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tutorialpb_tutorial_proto_rawDescOnce sync.Once
	file_tutorialpb_tutorial_proto_rawDescData = file_tutorialpb_tutorial_proto_rawDesc
)

func file_tutorialpb_tutorial_proto_rawDescGZIP() []byte {
	file_tutorialpb_tutorial_proto_rawDescOnce.Do(func() {
		file_tutorialpb_tutorial_proto_rawDescData = protoimpl.X.CompressGZIP(file_tutorialpb_tutorial_proto_rawDescData)
	})
	return file_tutorialpb_tutorial_proto_rawDescData
}

var file_tutorialpb_tutorial_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tutorialpb_tutorial_proto_goTypes = []interface{}{
	(*PrintStrRequest)(nil),  // 0: grpc_tutorial.PrintStrRequest
	(*PrintStrResponce)(nil), // 1: grpc_tutorial.PrintStrResponce
}
var file_tutorialpb_tutorial_proto_depIdxs = []int32{
	0, // 0: grpc_tutorial.Printer.PrintStr:input_type -> grpc_tutorial.PrintStrRequest
	1, // 1: grpc_tutorial.Printer.PrintStr:output_type -> grpc_tutorial.PrintStrResponce
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tutorialpb_tutorial_proto_init() }
func file_tutorialpb_tutorial_proto_init() {
	if File_tutorialpb_tutorial_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tutorialpb_tutorial_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrintStrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tutorialpb_tutorial_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrintStrResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tutorialpb_tutorial_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tutorialpb_tutorial_proto_goTypes,
		DependencyIndexes: file_tutorialpb_tutorial_proto_depIdxs,
		MessageInfos:      file_tutorialpb_tutorial_proto_msgTypes,
	}.Build()
	File_tutorialpb_tutorial_proto = out.File
	file_tutorialpb_tutorial_proto_rawDesc = nil
	file_tutorialpb_tutorial_proto_goTypes = nil
	file_tutorialpb_tutorial_proto_depIdxs = nil
}
